import type {
  OpeningBalance,
  SparePartItem,
  StockLocation,
} from "./types";

export const spareParts: SparePartItem[] = [
  {
    id: "part-001",
    partCode: "SP-HVAC-FLT-001",
    name: "AHU Air Filter",
    category: "HVAC",
    unitOfMeasure: "piece",
    manufacturer: "Carrier",
    manufacturerPartNumber: "FLT-39M-01",
    description: "Replacement air filter for AHU service.",
    status: "active",
    reorderLevel: 10,
    preferredWarehouseId: "loc-wh-001",
    notes: "Keep minimum stock available for monthly AHU servicing.",
  },
  {
    id: "part-002",
    partCode: "SP-GEN-OIL-001",
    name: "Generator Engine Oil",
    category: "Generator",
    unitOfMeasure: "litre",
    manufacturer: "Cummins",
    manufacturerPartNumber: "OIL-C15-01",
    description: "Engine oil used during generator servicing.",
    status: "active",
    reorderLevel: 20,
    preferredWarehouseId: "loc-wh-001",
  },
  {
    id: "part-003",
    partCode: "SP-EL-FUSE-001",
    name: "Industrial Fuse 32A",
    category: "Electrical",
    unitOfMeasure: "piece",
    manufacturer: "Schneider Electric",
    manufacturerPartNumber: "FUSE-32A-01",
    description: "32A replacement fuse for electrical maintenance.",
    status: "active",
    reorderLevel: 8,
    preferredWarehouseId: "loc-wh-002",
  },
  {
    id: "part-004",
    partCode: "SP-FS-SEAL-001",
    name: "Fire Pump Mechanical Seal",
    category: "Fire Safety",
    unitOfMeasure: "piece",
    manufacturer: "Armstrong",
    manufacturerPartNumber: "FP-SEAL-4380",
    description: "Replacement mechanical seal for fire pump maintenance.",
    status: "active",
    reorderLevel: 2,
    preferredWarehouseId: "loc-wh-002",
  },
  {
    id: "part-005",
    partCode: "SP-OLD-BELT-001",
    name: "Legacy AHU Drive Belt",
    category: "HVAC",
    unitOfMeasure: "piece",
    status: "inactive",
    reorderLevel: 0,
    preferredWarehouseId: "loc-wh-001",
    notes: "Inactive legacy part retained for historical records.",
  },
];

export const stockLocations: StockLocation[] = [
  {
    id: "loc-wh-001",
    code: "WH-HVM-C",
    name: "Harborview Central Warehouse",
    type: "warehouse",
    siteId: "site-001",
    status: "active",
  },
  {
    id: "loc-wh-002",
    code: "WH-NLL-A",
    name: "Northline Depot Warehouse",
    type: "warehouse",
    siteId: "site-003",
    status: "active",
  },
  {
    id: "loc-tech-001",
    code: "TECH-R-MEHTA",
    name: "Technician Stock - R. Mehta",
    type: "technician",
    technicianName: "R. Mehta",
    status: "active",
  },
  {
    id: "loc-tech-002",
    code: "TECH-S-ORTIZ",
    name: "Technician Stock - S. Ortiz",
    type: "technician",
    technicianName: "S. Ortiz",
    status: "active",
  },
];

export const openingBalances: OpeningBalance[] = [
  {
    id: "opening-001",
    itemId: "part-001",
    locationId: "loc-wh-001",
    quantity: 25,
    notes: "Initial warehouse stock for HVAC servicing.",
  },
  {
    id: "opening-002",
    itemId: "part-002",
    locationId: "loc-wh-001",
    quantity: 40,
    notes: "Initial generator service stock.",
  },
  {
    id: "opening-003",
    itemId: "part-003",
    locationId: "loc-wh-002",
    quantity: 12,
  },
  {
    id: "opening-004",
    itemId: "part-004",
    locationId: "loc-wh-002",
    quantity: 3,
  },
  {
    id: "opening-005",
    itemId: "part-001",
    locationId: "loc-tech-001",
    quantity: 2,
  },
  {
    id: "opening-006",
    itemId: "part-002",
    locationId: "loc-tech-002",
    quantity: 5,
  },
];
