import type {
  Asset,
  AssetDocument,
  Customer,
  MaintenancePlan,
  MockWorkOrder,
  ServiceHistoryEntry,
  Site,
} from "./types";

export const customers: Customer[] = [
  {
    id: "cust-001",
    name: "Harborview Malls",
    code: "HVM",
  },
  {
    id: "cust-002",
    name: "Northline Logistics",
    code: "NLL",
  },
  {
    id: "cust-003",
    name: "CityCare Clinics",
    code: "CCC",
  },
];

export const sites: Site[] = [
  {
    id: "site-001",
    customerId: "cust-001",
    name: "Harborview Central",
    code: "HVM-C",
    address: "120 Market Street, Downtown",
  },
  {
    id: "site-002",
    customerId: "cust-001",
    name: "Harborview East Wing",
    code: "HVM-E",
    address: "88 East Promenade",
  },
  {
    id: "site-003",
    customerId: "cust-002",
    name: "Northline Depot A",
    code: "NLL-A",
    address: "450 Industrial Park Road",
  },
  {
    id: "site-004",
    customerId: "cust-003",
    name: "CityCare Main Campus",
    code: "CCC-M",
    address: "15 Wellness Avenue",
  },
];

export const assets: Asset[] = [
  {
    id: "asset-001",
    assetCode: "AST-HVAC-1001",
    name: "Rooftop AHU-3",
    category: "HVAC",
    customerId: "cust-001",
    siteId: "site-001",
    location: "Roof Level, Zone C",
    status: "active",
    serialNumber: "AHU3-88214",
    model: "Carrier 39M",
    installationDate: "2022-03-15",
    warrantyExpiry: "2027-03-15",
    notes: "Serves retail atrium and food court.",
    nextMaintenanceDate: "2026-09-18",
  },
  {
    id: "asset-002",
    assetCode: "AST-GEN-2040",
    name: "Backup Generator G2",
    category: "Generator",
    customerId: "cust-002",
    siteId: "site-003",
    location: "Plant Room B",
    status: "active",
    serialNumber: "GEN-2040-77",
    model: "Cummins C150D5",
    installationDate: "2021-11-02",
    warrantyExpiry: "2026-11-02",
    nextMaintenanceDate: "2026-09-12",
  },
  {
    id: "asset-003",
    assetCode: "AST-FS-3110",
    name: "Fire Pump FP-1",
    category: "Fire Safety",
    customerId: "cust-003",
    siteId: "site-004",
    location: "Basement Fire Room",
    status: "under-maintenance",
    serialNumber: "FP1-55190",
    model: "Armstrong 4380",
    installationDate: "2020-06-20",
    warrantyExpiry: "2025-06-20",
    notes: "Warranty expired — track renewal separately.",
    nextMaintenanceDate: "2026-09-10",
  },
  {
    id: "asset-004",
    assetCode: "AST-EL-1508",
    name: "Main Distribution Panel MDP-A",
    category: "Electrical",
    customerId: "cust-001",
    siteId: "site-002",
    location: "Electrical Room Level 1",
    status: "inactive",
    model: "Schneider Prisma Plus",
    installationDate: "2019-09-01",
    warrantyExpiry: "2024-09-01",
    notes: "Temporarily offline during East Wing renovation.",
    nextMaintenanceDate: "2026-10-01",
  },
];

export const maintenancePlans: MaintenancePlan[] = [
  {
    id: "plan-001",
    assetId: "asset-001",
    planName: "AHU monthly filter and belt check",
    frequency: "monthly",
    startDate: "2026-01-18",
    nextDueDate: "2026-09-18",
    checklist: [
      "Inspect filters and replace if dirty",
      "Check belt tension and alignment",
      "Verify drain pan and condensate line",
      "Record supply/return temperatures",
    ],
    status: "active",
  },
  {
    id: "plan-002",
    assetId: "asset-002",
    planName: "Generator weekly run test",
    frequency: "weekly",
    startDate: "2026-06-06",
    nextDueDate: "2026-09-12",
    checklist: [
      "Visual inspection for leaks",
      "Check coolant and oil levels",
      "Start and run under no-load for 10 minutes",
      "Log voltage and frequency readings",
    ],
    status: "active",
  },
  {
    id: "plan-003",
    assetId: "asset-003",
    planName: "Fire pump monthly operational test",
    frequency: "monthly",
    startDate: "2026-02-10",
    nextDueDate: "2026-09-10",
    checklist: [
      "Confirm controller in automatic mode",
      "Run pump and verify pressure",
      "Inspect packing gland for leakage",
      "Test supervisory signals",
    ],
    status: "active",
  },
  {
    id: "plan-004",
    assetId: "asset-004",
    planName: "MDP thermographic scan",
    frequency: "monthly",
    startDate: "2026-04-01",
    nextDueDate: "2026-10-01",
    checklist: [
      "Confirm isolation procedures",
      "Capture thermal images of bus connections",
      "Compare against previous baseline",
    ],
    status: "paused",
  },
];

export const serviceHistory: ServiceHistoryEntry[] = [
  {
    id: "hist-001",
    assetId: "asset-001",
    planId: "plan-001",
    workOrderId: "mwo-9001",
    performedOn: "2026-08-18",
    summary: "Monthly AHU service completed; filters replaced.",
    performedBy: "Tech. R. Mehta",
    outcome: "completed",
  },
  {
    id: "hist-002",
    assetId: "asset-002",
    planId: "plan-002",
    workOrderId: "mwo-9002",
    performedOn: "2026-09-05",
    summary: "Weekly generator run test within acceptable limits.",
    performedBy: "Tech. S. Ortiz",
    outcome: "completed",
  },
  {
    id: "hist-003",
    assetId: "asset-003",
    performedOn: "2026-08-02",
    summary: "Seal leak noted; parts ordered before full PM.",
    performedBy: "Supervisor A. Khan",
    outcome: "deferred",
  },
];

export const assetDocuments: AssetDocument[] = [
  {
    id: "doc-001",
    assetId: "asset-001",
    name: "Carrier 39M Operation Manual.pdf",
    type: "manual",
    uploadedOn: "2022-03-20",
    placeholderUrl: "#document-placeholder/manual-ahu3",
  },
  {
    id: "doc-002",
    assetId: "asset-001",
    name: "AHU-3 Warranty Certificate.pdf",
    type: "warranty",
    uploadedOn: "2022-03-20",
    placeholderUrl: "#document-placeholder/warranty-ahu3",
  },
  {
    id: "doc-003",
    assetId: "asset-002",
    name: "Generator commissioning photo.jpg",
    type: "photo",
    uploadedOn: "2021-11-05",
    placeholderUrl: "#document-placeholder/photo-gen-g2",
  },
  {
    id: "doc-004",
    assetId: "asset-003",
    name: "Fire pump inspection certificate.pdf",
    type: "certificate",
    uploadedOn: "2025-01-12",
    placeholderUrl: "#document-placeholder/cert-fp1",
  },
];

export const mockWorkOrders: MockWorkOrder[] = [
  {
    id: "mwo-001",
    reference: "WO-PM-4401",
    assetId: "asset-003",
    planId: "plan-003",
    title: "PM handoff: Fire pump monthly operational test",
    status: "scheduled",
    scheduledDate: "2026-09-10",
    notes: "Generated from active maintenance plan for demo handoff.",
  },
  {
    id: "mwo-002",
    reference: "WO-PM-4402",
    assetId: "asset-002",
    planId: "plan-002",
    title: "PM handoff: Generator weekly run test",
    status: "new",
    scheduledDate: "2026-09-12",
  },
  {
    id: "mwo-9001",
    reference: "WO-PM-4388",
    assetId: "asset-001",
    planId: "plan-001",
    title: "PM completed: AHU monthly filter and belt check",
    status: "completed",
    scheduledDate: "2026-08-18",
    completedOn: "2026-08-18",
    notes: "Sample completed handoff used by service history.",
  },
];
